/* Fonte única de dados institucionais. Alterações devem ser validadas pela direção. */
window.ASAS_CONFIG = Object.freeze({
  organization: {
    publicName: "Rede ASAS Brasil",
    legalName: "Associação Shekinah de Assistência Social — ASAS",
    cnpj: "01.160.544/0001-83",
    foundedYear: 1996,
    address: "Rua Alair Pereira da Silva, 205 — Taquaril, Belo Horizonte/MG",
    email: "contato@redeasas.org.br",
    whatsappDisplay: "(31) 98960-8865",
    whatsappNumber: "5531989608865",
    instagram: "https://www.instagram.com/redeasasbr/",
    facebook: null,
    foundedDate: null,
    lastUpdated: "2026-08-11",
  },
  urls: {
    canonical: "https://redeasas.org.br",
    officialDomain: "https://redeasas.org.br",
    published: "https://redeasas.org.br",
    campaign: "https://benfeitoria.com/projeto/ampliacaoredeasasbrasil",
  },
  donation: {
    pixKey: "01.160.544/0001-83",
    qrImage: "assets/images/qrcode-pix.jpeg",
    beneficiary: "Associação Shekinah de Assistência Social — ASAS",
    purpose: "Construção Prédio Rede ASAS",
    verifiedAt: "2026-08-09",
  },
  metrics: [
    { id: "people", value: "+580", label: "pessoas alcançadas diariamente (informação institucional)", concept: "Estimativa informada pela instituição; não equivale ao total de atendimentos e ainda não possui base nominal consolidada disponível para auditoria.", period: "Rotina diária informada; período de apuração não documentado", status: "not-validated", source: "Comunicação institucional fornecida à equipe do site", baseDate: null, methodology: "Critério de pessoa única e processo de consolidação ainda não documentados", updatedAt: "2026-08-10" },
    { id: "children", value: "+140", label: "crianças na Educação Infantil (informação institucional)", concept: "Estimativa informada pela instituição; ainda é necessário distinguir matrículas ativas, frequência e acompanhamento.", period: "Período letivo não informado", status: "not-validated", source: "Comunicação institucional fornecida à equipe do site", baseDate: null, methodology: "Critério de matrícula ou acompanhamento ainda não documentado", updatedAt: "2026-08-10" },
    { id: "programs", value: "11", label: "frentes de atuação (informação institucional)", concept: "Quantidade divulgada institucionalmente; a lista pública do site contém iniciativas e projetos que ainda precisam de classificação oficial.", period: "Situação informada em 2026", status: "not-validated", source: "Comunicação institucional e inventário do site", baseDate: "2026", methodology: "Critério entre projeto, serviço e frente de atuação ainda não formalizado", updatedAt: "2026-08-10" },
    { id: "history", value: "30", label: "anos de atuação em 2026", concept: "Tempo decorrido desde 13 de fevereiro de 1996, data de fundação informada pela instituição.", period: "13/02/1996–13/02/2026", status: "institutional-validated", source: "Data de fundação institucional informada para o site", baseDate: "2026-02-13", methodology: "Anos completos transcorridos entre as datas", updatedAt: "2026-08-10" },
  ],
  impactDimensions: {
    peopleUnique: null,
    servicesDelivered: null,
    childrenEnrolled: null,
    childrenFollowed: null,
    familiesReached: null,
    participantsByProject: null,
    monthlyResults: null,
    annualResults: null,
  },
  building: {
    area: "640 m²",
    estimate: "R$ 3.321.980,35",
    estimateShort: "R$ 3,32 milhões",
    lowScenario: "R$ 2.500.711,86",
    highScenario: "R$ 4.533.850,74",
    budgetDate: "julho de 2026",
    status: "Estimativa preliminar — não constitui orçamento executivo",
    structuralProjectDate: "2026-07-14",
    structuralSheetsReceived: 17,
    foundationElements: { caissons: 17, piles: 6 },
    technicalSource: "Pranchas 01 e 02 do projeto estrutural, emissão inicial de 14/07/2026, iSATO Engenharia; conjunto de 17 arquivos estruturais fornecido pela instituição.",
    budgetSource: "Orçamento_Preliminar_Rede_ASAS_Brasil.xlsx, recebido em julho de 2026.",
    raised: null,
    raisedValue: null,
    goalConfirmed: false,
    reconciliationDate: null,
    currentStage: null,
  },
  transparencyDocuments: [],
  governance: { board: [], certifications: [], authorizedPartners: [], integrityChannel: null, childProtectionPolicy: null },
  contribution: { totalInvested: null, balance: null, recurringAvailable: false, cardsAvailable: false, boletoAvailable: false, receiptAutomationAvailable: false },
  integrations: {
    crm: null,
    newsletter: null,
    analytics: { measurementId: "G-XJ3L8N2SCW" },
    searchConsole: { verificationToken: "cRd9OG2MlK-4SFn41wg5Sc2_uhJGiycnTo5fets120w" },
    formService: "Supabase Edge Function — projeto exclusivo Rede ASAS Brasil",
  },
  forms: {
    endpoint: "https://yljvlllrvibyongccgmz.supabase.co/functions/v1/lead-capture",
    mode: "secure-api-with-email-fallback",
    allowedOrigins: ["https://redeasas.org.br", "https://www.redeasas.org.br", "https://redeasas.github.io"],
  },
  publicReviewMessage: "Dados institucionais em processo de atualização.",
});
