/* Fonte única de dados institucionais. Alterações devem ser validadas pela direção. */
window.ASAS_CONFIG = Object.freeze({
  organization: {
    publicName: "Rede ASAS Brasil",
    legalName: "Associação Shekinah de Assistência Social — ASAS",
    cnpj: "01.160.544/0001-83",
    foundedYear: 1996,
    address: "Rua Alair Pereira da Silva, 205 — Taquaril, Belo Horizonte/MG",
    email: "contato@redeasas.org.br",
    whatsappDisplay: "(31) 98960-8865",
    whatsappNumber: "5531989608865",
    instagram: "https://www.instagram.com/redeasasbr/",
    facebook: null,
    foundedDate: null,
    lastUpdated: "2026-08-09",
  },
  urls: {
    canonical: "https://redeasas.github.io/site",
    officialDomain: "https://redeasas.org.br",
    published: "https://redeasas.github.io/site",
    campaign: "https://benfeitoria.com/projeto/ampliacaoredeasasbrasil",
  },
  donation: {
    pixKey: "01.160.544/0001-83",
    qrImage: "assets/images/qrcode-pix.jpeg",
    beneficiary: "Associação Shekinah de Assistência Social — ASAS",
    purpose: "Construção Prédio Rede ASAS",
    verifiedAt: "2026-08-09",
  },
  metrics: [
    { id: "people", value: "+580", label: "vidas atendidas diariamente", concept: "Pessoas alcançadas pelas iniciativas informadas pela instituição; não equivale ao total de atendimentos.", period: null, status: "institutional-review", source: null, baseDate: null, methodology: null, updatedAt: null },
    { id: "children", value: "+140", label: "crianças na Educação Infantil", concept: "Crianças matriculadas ou acompanhadas; critério exato em validação institucional.", period: null, status: "institutional-review", source: null, baseDate: null, methodology: null, updatedAt: null },
    { id: "programs", value: "11", label: "frentes de atuação social", concept: "Frentes ou iniciativas informadas pela instituição; relação e critério de contagem em validação.", period: null, status: "institutional-review", source: null, baseDate: null, methodology: null, updatedAt: null },
    { id: "history", value: "30", label: "anos de atuação em 2026", concept: "Tempo decorrido desde o ano de fundação informado, 1996.", period: "1996–2026", status: "institutional", source: "Informação institucional: fundação em 1996", baseDate: "2026", methodology: "Diferença entre os anos de 2026 e 1996", updatedAt: "2026-08-09" },
  ],
  impactDimensions: {
    peopleUnique: null,
    servicesDelivered: null,
    childrenEnrolled: null,
    childrenFollowed: null,
    familiesReached: null,
    participantsByProject: null,
    monthlyResults: null,
    annualResults: null,
  },
  building: {
    area: "640 m²",
    estimate: "R$ 3.321.980,35",
    estimateShort: "R$ 3,32 milhões",
    lowScenario: "R$ 2.500.711,86",
    highScenario: "R$ 4.533.850,74",
    budgetDate: "julho de 2026",
    status: "Estimativa preliminar — não constitui orçamento executivo",
    raised: null,
    raisedValue: null,
    goalConfirmed: false,
    reconciliationDate: null,
    currentStage: null,
  },
  transparencyDocuments: [],
  governance: { board: [], certifications: [], authorizedPartners: [], integrityChannel: null, childProtectionPolicy: null },
  contribution: { totalInvested: null, balance: null, recurringAvailable: false, cardsAvailable: false, boletoAvailable: false, receiptAutomationAvailable: false },
  integrations: { crm: null, newsletter: null, analytics: null, formService: null },
  forms: { endpoint: null, mode: "email-fallback" },
  publicReviewMessage: "Dados institucionais em processo de atualização.",
});
