(async () => {
  const authContext = await window.ASAS_AUTH_READY;
  const view = document.body.dataset.hubView || "crm";
  const labels = { mantenedor:"Ficha 360°", crm:"CRM", financeiro:"Financeiro", empresas:"Empresas", voluntarios:"Voluntários", impacto:"Impacto", ia:"IA ASAS" };
  const prefix = view === "mantenedor" ? "../../" : "../";
  const navigation = [["../asas-hub.html","Dashboard"],["mantenedores/demo.html","Mantenedores"],["financeiro.html","Financeiro"],["crm.html","CRM"],["empresas.html","Empresas"],["voluntarios.html","Voluntários"],["impacto.html","Impacto"],["ia.html","IA ASAS"]];
  const cards = (items) => `<section class="hub-kpis">${items.map(([a,b,c])=>`<article><small>${a}</small><strong>${b}</strong><span>${c}</span></article>`).join("")}</section>`;
  const emptyRows = (columns, rows=5) => `<div class="hub-table" role="table"><div class="hub-tr hub-th">${columns.map(x=>`<span>${x}</span>`).join("")}</div>${Array.from({length:rows},(_,i)=>`<div class="hub-tr"><span>Registro fictício ${i+1}</span>${columns.slice(1).map(()=>`<span>—</span>`).join("")}</div>`).join("")}</div>`;
  const screens = {
    mantenedor: `<div class="hub-profile"><div class="hub-avatar">EX</div><div><small>Mantenedor demonstrativo</small><h2>Pessoa Exemplo</h2><p>ASA #DEMO · Contato protegido · Belo Horizonte/MG</p></div><span class="hub-status">ATIVO — MOCK</span></div>${cards([["Contribuição mensal","R$ —","Gateway não conectado"],["Total contribuído","R$ —","Sem conciliação"],["Indicações","—","Sem dados reais"],["Origem","Demonstração","Não rastreada"]])}<div class="hub-tabs"><button class="active">Resumo</button><button>Pagamentos</button><button>Relacionamento</button><button>Indicações</button><button>Dados pessoais</button><button>Documentos</button></div><section class="hub-two"><article class="hub-panel"><h2>Histórico de pagamentos</h2>${emptyRows(["Competência","Valor","Status","Método"],4)}</article><article class="hub-panel"><h2>Resumo do relacionamento</h2><p class="hub-empty">Nenhuma interação real. Quando o backend estiver ativo, alterações sensíveis gerarão trilha de auditoria.</p><h3>Notas da equipe</h3><p>Campo demonstrativo com acesso condicionado ao perfil autorizado.</p></article></section>`,
    crm: `<div class="hub-toolbar"><input data-hub-search placeholder="Buscar contatos autorizados…"><button disabled>Filtros</button><button disabled>+ Novo lead</button></div><p class="hub-note">Dados reais protegidos por sessão, perfil de acesso e trilha de auditoria. Exibição limitada ao necessário para triagem.</p><div class="hub-kanban" data-kanban><p class="hub-empty">Carregando contatos com segurança…</p></div>`,
    financeiro: `${cards([["Receita total","R$ —","Sem gateway"],["Receita recorrente","R$ —","Sem webhook"],["Doações pontuais","R$ —","Não conciliado"],["Pendências","—","Sem dados reais"]])}<section class="hub-two"><article class="hub-panel"><h2>Evolução da receita</h2><div class="hub-chart-empty">Gráfico aguardando integração financeira</div></article><article class="hub-panel"><h2>Origem da receita</h2><div class="hub-donut"><b>SEM<br>DADOS</b></div></article></section><article class="hub-panel"><h2>Movimentações</h2>${emptyRows(["Data","Descrição","Categoria","Valor","Status"],5)}<p class="hub-note">Contrato previsto: eventos idempotentes do gateway por webhook; nenhum dado completo de cartão será armazenado.</p></article>`,
    empresas: `${cards([["Leads","—","Demonstração"],["Em negociação","—","Demonstração"],["Parceiros","—","Demonstração"],["Inativos","—","Demonstração"]])}<article class="hub-panel"><h2>Gestão de parcerias</h2>${emptyRows(["Empresa","Contato","Interesse","Status","Responsável","Próxima ação"],6)}</article>`,
    voluntarios: `${cards([["Novos","—","Sem dados pessoais"],["Entrevista","—","Sem agenda"],["Ativos","—","Sem validação"],["Pausados","—","Demonstração"]])}<article class="hub-panel"><h2>Cadastros de voluntariado</h2>${emptyRows(["Nome","Área","Disponibilidade","Status","Projeto","Último contato"],6)}<p class="hub-note">LGPD: coletar somente dados necessários, consentimento e documentos aplicáveis ao projeto.</p></article>`,
    impacto: `${cards([["Crianças atendidas","—","Em validação"],["Famílias atendidas","—","Em validação"],["Atividades","—","Em validação"],["Atendimentos","—","Em validação"]])}<section class="hub-two"><article class="hub-panel"><h2>Indicadores</h2>${emptyRows(["Indicador","Período","Fonte","Responsável","Status"],4)}</article><article class="hub-panel"><h2>O que suas ASAS fizeram este mês</h2><p class="hub-empty">Conteúdo ainda não publicado. Somente indicadores com status APROVADO ou PUBLICADO poderão alimentar o site e Minha ASA.</p><div class="hub-workflow"><span>Rascunho</span><i>→</i><span>Em validação</span><i>→</i><span>Aprovado</span><i>→</i><span>Publicado</span></div></article></section>`,
    ia: `<div class="hub-toolbar"><input data-hub-search placeholder="Buscar conteúdo aprovado…"><button data-test-ia>Testar IA</button><button disabled>+ Novo conteúdo</button></div><section class="hub-two"><aside class="hub-panel"><h2>Categorias</h2><ul class="hub-categories">${["Institucional","História","Projetos","Creche","Impacto","Transparência","1.000 ASAS","Doações","Voluntariado","Empresas","Novo prédio","Contatos"].map(x=>`<li>${x}</li>`).join("")}</ul></aside><article class="hub-panel"><h2>Base de conhecimento</h2>${emptyRows(["Título","Categoria","Status","Fonte"],6)}<p class="hub-note">A IA pública só poderá consultar conteúdos com status PUBLICADO e fonte aprovada.</p></article></section>`
  };
  document.body.innerHTML = `<aside class="hub-sidebar"><a class="hub-brand" href="${prefix}index.html"><span><img src="${prefix}assets/images/logo-rede-asas-oficial.png" alt="Rede ASAS Brasil"></span></a><p>ASAS HUB<small>Ambiente demonstrativo</small></p><nav>${navigation.map(([href,label])=>`<a${label===labels[view]||label===view.toUpperCase()?' class="active"':''} href="${view==='mantenedor'?'../':''}${href}">${label}</a>`).join("")}</nav><a class="hub-back" href="${prefix}index.html">← Voltar ao site</a></aside><main class="hub-main"><div class="hub-demo">Demonstração · sem dados pessoais, financeiros ou operacionais reais</div><header><div><p>ASAS HUB / ${labels[view]}</p><h1>${labels[view]}</h1><span>Protótipo funcional para validação de arquitetura e fluxo.</span></div><button aria-label="Perfil demonstrativo">AS</button></header>${screens[view]}<footer><strong>RBAC previsto</strong><span>Administrador · Financeiro · Relacionamento · Projetos · Leitura/Auditoria</span></footer></main>`;
  document.querySelector("[data-hub-search]")?.addEventListener("input",e=>{const term=e.target.value.toLowerCase();document.querySelectorAll("[data-card],.hub-tr:not(.hub-th)").forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(term));});
  document.querySelectorAll("[data-stage]").forEach(select=>select.addEventListener("change",()=>{select.closest("[data-card]").dataset.pendingMove="true"; select.insertAdjacentHTML("afterend",'<small class="hub-warning">Alteração apenas visual; não foi salva.</small>');}));
  document.querySelector("[data-test-ia]")?.addEventListener("click",()=>alert("Modo de teste: nenhuma pergunta ou resposta será publicada."));

  if (view === "crm" && !authContext.demo) {
    const escape = (value) => String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
    const stages = [
      ["Novo lead", ["novo_lead"]], ["Qualificação", ["qualificacao","diagnostico"]],
      ["Contato realizado", ["contato_realizado"]], ["Negociação", ["reuniao","proposta","negociacao"]],
      ["Parceria", ["parceria","execucao","relatorio","renovacao","pos_parceria"]]
    ];
    const fields = "id,created_at,form_type,name,interest,organization,project_interest,support_type,monthly_amount_interest,pipeline_stage,assigned_to,last_contacted_at";
    const response = await window.ASAS_AUTH.request(`/rest/v1/asas_leads?select=${fields}&order=created_at.desc&limit=200`, {}, authContext.user.access_token || window.ASAS_AUTH.readSession().access_token);
    const kanban = document.querySelector("[data-kanban]");
    if (!response.ok) kanban.innerHTML = '<p class="hub-empty">Não foi possível carregar os contatos. Verifique o perfil de acesso ou tente novamente.</p>';
    else {
      const leads = await response.json();
      const card = lead => `<article data-card><strong>${escape(lead.name)}</strong><small>${escape(lead.organization || lead.form_type)}</small><p>Interesse: ${escape(lead.project_interest || lead.interest || lead.support_type || "não classificado")}<br>Origem: ${escape(lead.form_type)}<br>Recebido: ${new Date(lead.created_at).toLocaleDateString("pt-BR")}</p>${lead.monthly_amount_interest ? `<b>Interesse mensal: ${escape(lead.monthly_amount_interest)}</b>` : ""}</article>`;
      kanban.innerHTML = stages.map(([label,values]) => { const matches = leads.filter(lead => values.includes(lead.pipeline_stage)); return `<section><h2>${label}<span>${matches.length}</span></h2>${matches.length ? matches.map(card).join("") : '<p class="hub-empty">Sem contatos</p>'}</section>`; }).join("");
    }
  }
})();
